services:
  qdrant:
    image: dockerhub.timeweb.cloud/qdrant/qdrant:latest
    container_name: rlt_qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rlt_django
    command: bash -c "cd RLT_project && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8080:8000"

    depends_on:
      qdrant:
        condition: service_started

    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OLLAMA_HOST=http://host.docker.internal:11434
      - KAFKA_URL=kafka:29092
      - LLM_REQUEST_TOPIC=${LLM_REQUEST_TOPIC}
      - LLM_RESPONSE_TOPIC=${LLM_RESPONSE_TOPIC}

    networks:
      - default
      - shared


networks:
  shared:
    external: true
    name: rlt_hack_network