# FROM dockerhub.timeweb.cloud/library/python:3.11-slim

FROM python:3.13-slim
WORKDIR /app

# Установка системных зависимостей
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Ставим PyTorch базовый (CPU версия, отлично работает на Mac) torchvision torchaudio
RUN pip3 install torch --extra-index-url https://download.pytorch.org/whl/cpu

# Ставим остальные зависимости проекта
COPY requirements.txt .
RUN pip3 install -r requirements.txt

# Копируем код
COPY . .
