services:
  qdrant:
    image: dockerhub.timeweb.cloud/qdrant/qdrant:latest
    container_name: rlt_qdrant
    restart: unless-stopped
    ports:
      - "${QDRANT_BIND_ADDRESS:-127.0.0.1}:6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  redis:
    image: redis:7-alpine
    container_name: rlt_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

  web:
    build:
      context: .
    container_name: rlt_django

    command: >
      bash -c "
        python RLT_project/manage.py migrate &&
        python RLT_project/manage.py runserver 0.0.0.0:8000
      "

    volumes:
      - .:/app
      - python_cache:/root/.cache

    ports:
      - "8001:8000"

    depends_on:
      - qdrant
      - redis

    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      QDRANT_MODE: server

      AUTO_INDEX_ON_START: "false"

      OLLAMA_HOST: http://host.docker.internal:11434

      KAFKA_URL: kafka:29092
      LLM_REQUEST_TOPIC: llm-requests
      LLM_RESPONSE_TOPIC: llm-responses

    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  qdrant_data:
  redis_data:
  python_cache:
