# Chat event names
EVENT_GENERATION_RESTORE = "GENERATION_RESTORE"
EVENT_MESSAGE_RESPONSE = "MESSAGE_RESPONSE"
EVENT_NEW_TOKEN = "NEW_TOKEN"
EVENT_END_GENERATION = "END_GENERATION"
EVENT_NEW_MESSAGE = "NEW_MESSAGE"

# Event statuses
STATUS_OK = "OK"